name: snap CI
on: ["pull_request"]
jobs:
  test:
    runs-on: Dell-Ubuntu
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      - name: Build snap
        run: |
          snapcraft -d snap --destructive-mode
